// <auto-generated />
using System;
using Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(WorkoutContext))]
    [Migration("20260213054252_AddUserIdToWorkouts")]
    partial class AddUserIdToWorkouts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Infrastructure.Database.Tables.Exercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<int?>("Equipment")
                        .HasColumnType("integer");

                    b.Property<int?>("Force")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<string[]>("Instructions")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int?>("Mechanic")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.PrimitiveCollection<int[]>("PrimaryMuscles")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.PrimitiveCollection<int[]>("SecondaryMuscles")
                        .HasColumnType("integer[]");

                    b.HasKey("Id");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("Infrastructure.Database.Tables.Workout", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("TotalDurationMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("WorkoutDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id", "UserId");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkoutDate");

                    b.ToTable("Workouts");
                });

            modelBuilder.Entity("Infrastructure.Database.Tables.WorkoutActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid");

                    b.Property<int>("Repetitions")
                        .HasColumnType("integer");

                    b.Property<double>("WeightKg")
                        .HasColumnType("double precision");

                    b.Property<Guid>("WorkoutId")
                        .HasColumnType("uuid");

                    b.Property<string>("WorkoutUserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("WorkoutId", "WorkoutUserId");

                    b.ToTable("WorkoutActivities");
                });

            modelBuilder.Entity("Infrastructure.Database.Tables.WorkoutActivity", b =>
                {
                    b.HasOne("Infrastructure.Database.Tables.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infrastructure.Database.Tables.Workout", "Workout")
                        .WithMany("WorkoutActivities")
                        .HasForeignKey("WorkoutId", "WorkoutUserId");

                    b.Navigation("Exercise");

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("Infrastructure.Database.Tables.Workout", b =>
                {
                    b.Navigation("WorkoutActivities");
                });
#pragma warning restore 612, 618
        }
    }
}
